### ISSUE TITLE
V2: Debugger not loading

### ISSUE THREAD

**Issue by saadbahir** [browserless/browserless#4139]
**Describe the bug**

In `browserless/chrome:v2.14.0` the debugger page doesn't load and the console shows errors while loading a number of js scripts

<img width="1678" alt="Screenshot 2024-06-27 at 09 24 27" src="https://github.com/browserless/browserless/assets/115225167/6f15e14e-a7b4-4db2-a76c-c1d7cd3eaa75">

All the js scripts have an HTML structure, is this normal?
<img width="412" alt="Screenshot 2024-06-27 at 09 28 06" src="https://github.com/browserless/browserless/assets/115225167/cbb6291a-e2de-4b72-b504-650559b71bdd">
<img width="172" alt="Screenshot 2024-06-27 at 09 28 15" src="https://github.com/browserless/browserless/assets/115225167/40904f6c-a9a0-4926-a996-1e9b5c877dea">

**Comment by jjacobsson** [comment]
My debugger looked like that when I tried to access it without the "?token=<your token>" at the end of the url.

See the warning here about the token: https://docs.browserless.io/docker/docker-quickstart/

**Comment by jjacobsson** [comment]
Ahem, so after a bunch of fiddling and head-scratching: 

`https://<yourdomain/host/whatever>/debugger**/**?token=<your token>` <- Works
`https://<yourdomain/host/whatever>/debugger?token=<your token>` <- Does not work. 

Just thought I would add that...

**Comment by andyMrtnzP** [comment]
That trailing `/` is not a matter of style, but a necessity, since the browser will automatically load the index in the context of the current path. So, the debugger page is _technically_ `localhost/debugger/index.html`. Meaning that, going to `localhost/debugger/`, the browser will try to load relative-assets (like `router.js`) from `localhost/debugger/router.js`. Going to `localhost/debugger` on the other hand, will try to load the assets as `localhost/router.js`.

_However_, regardless of anything, the page _should_ automatically add the trailing slash to the url and redirect, which is evidently failing. Thanks for raising the issue!

**Comment by joelgriffith** [comment]
We’ve added some trailing slash fixes in recent releases so this should hopefully mitigate things like this!

**Comment by white0dew** [comment]
你好，请问你解决了这个问题吗

**Comment by body-clock** [comment]
Still experiencing the necessity to add the trailing `/` in the debugger URL with `ghcr.io/browserless/chromium:v2.27.0`

**Comment by williamoliveira** [comment]
problem still persists in `ghcr.io/browserless/chrome:v2.34.1`

**Comment by barart** [comment]
Still on 2.37.0

**Comment by lluisd** [comment]
still on 2.38.2
