### ISSUE TITLE
How to get the response headers when getting url content

### ISSUE THREAD

**Issue by moda20** [browserless/browserless#4465]
I am trying to get the response headers from the target website when getting content via the rest API, `/content`. 
right now i only get `x-response-code`, `ip`, `port`, `status`, and `url` but not the headers returned by the target url. 

i am using the rest API on a simple container configuration.

**Comment by joelgriffith** [comment]
I see, yeah this is something that's going to get tricky since it's hard to differentiate and distinguish the _browserless server_'s headers from the underlying site's headers.

I think for cases like these it's probably just easier to write a call to the /function API since it allows you to craft your own JSON response, which can capture any of these types of data points (like headers). I understand it isn't as "off-the-shelf" but you'll get everything you'll want and nothing you don't.

Otherwise we risk crowding our existing APIs with a lot of information, having to document/support/test them, and really only some of those data-points will be useful to certain use-cases.
